name: Run Go Tests & Linter

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*'
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.3'
          cache: true

      - name: Run Go Tidy
        run: go mod tidy

      - name: Run Go Vet
        run: go vet ./...

      - name: Run Go Tests
        run: go test -v ./...

      - name: Install and run golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1.6
